version: 0.1

globalTimeout: 120
testSuiteTimeout: 120
testSuiteStep: 120

runson: win

concurrency: 2

pre:
  - npm install
  - npx playwright install

testDiscovery:
  type: raw
  mode: dynamic
  command: npx playwright test --list --reporter=json | node -e "const input = require('fs').readFileSync(0, 'utf8'); const data = JSON.parse(input); data.suites.forEach(suite => console.log(suite.file));"

testRunnerCommand: npx playwright test tests/$test --reporter=html,json,junit --output=test-results/

env:
  LT_USERNAME: $env:LT_USERNAME
  LT_ACCESS_KEY: $env:LT_ACCESS_KEY

cache:
  - node_modules
  - ~/.cache/ms-playwright

framework:
  name: playwright

report: true

uploadArtefacts:
  - name: test-results
    path:
      - test-results/**
  - name: playwright-report
    path:
      - playwright-report/**