version: 0.1

globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90

runson: win

concurrency: 2

autosplit: true

pre:
  - npm install
  - npx playwright install

testDiscovery:
  type: raw
  mode: dynamic
  command: npx playwright test --list --reporter=json

testRunnerCommand: npx playwright test --project=$HYPEREXECUTE_SPLIT_ID

env:
  LT_USERNAME: $LT_USERNAME
  LT_ACCESS_KEY: $LT_ACCESS_KEY
  PLAYWRIGHT_JUNIT_OUTPUT_NAME: results/junit-report.xml

secrets:
  - name: LT_USERNAME
  - name: LT_ACCESS_KEY

cache:
  - node_modules
  - ~/.cache/ms-playwright

framework:
  name: playwright
  defaultReports: false

report: true
partialReports:
  frameworkName: playwright
  location: results
  type: json

uploadArtefacts:
  - name: playwright-logs
    path:
      - results/**
  - name: test-videos
    path:
      - test-results/**/*.webm
  - name: test-screenshots
    path:
      - test-results/**/*.png