version: "0.1"
user: amitk26hexaware
key: '********'
testSuites: []
pre: [npm install, npx playwright install]
preDirectives:
    commands: [npm install, npx playwright install]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
env:
    LT_ACCESS_KEY: $env:LT_ACCESS_KEY
    LT_USERNAME: $env:LT_USERNAME
runson: win
concurrency: 2
testDiscovery:
    command: npx playwright test --list --reporter=json
    mode: dynamic
    type: raw
testRunnerCommand: npx playwright test $test
globalTimeout: 120
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 120
testSuiteStep: 120
jobID: 823de4fc-e2b1-41df-aa93-1a5c6ab2e7f8
uploadArtefacts:
    - name: test-results
      path:
        - test-results/**
      email:
        to: []
        metaInfo: []
        linkValidity: 0
    - name: playwright-report
      path:
        - playwright-report/**
      email:
        to: []
        metaInfo: []
        linkValidity: 0
codeDirectory: Playwright
report: true
framework:
    name: playwright
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: null
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
        otherApps: []
        customData: {}
        smartUI: null
        darkMode: false
        testRemarks: false
        autoGrantPermissions: false
        networkLogsOptions:
            captureContent: false
            excludeHosts: []
            includeHosts: []
        enableResultBundle: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
triggerSource: CLI
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: null
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: 01K5W83J1K8WAGD3QSVQ95SFCW
    name: LambdaTest Default Project
    type: custom
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig:
    vm: []
    storage:
        region: ""
        enabled: false
        name: ""
        platform: azure
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
globalPre:
    mode: ""
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
    cache: false
    yamlPath: null
    type: ""
    location: ""
globalPost:
    mode: ""
    commands: []
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
slackChannel: ""
whiteLabelProductTag: ""
sprofilePath: ""
ltOptions: {}
